### ISSUE TITLE
Fix/enable Shanghai fork

### ISSUE THREAD

**Issue by roman-khimov** [bane-labs/go-ethereum#113]
We don't have https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/shanghai.md enabled in our configs which makes us incompatible with the most recent Solidity tools producing PUSH0 (likely other problems can happen as well). Enabling it breaks dbft though (as well as clique), so this requires some fixes from the consensus part.

Refs. #110.

**Comment by AnnaShaleva** [comment]
From the brief glance Shanghai is not supported in the Clique because of https://eips.ethereum.org/EIPS/eip-3651 and because of the fact that in Clique Coinbase should be empty on checkpoint blocks. In dBFT we don't have checkpoint blocks and don't have such problem (Coinbase is always set in dBFT), thus I'd say we should allow Shanghai support in dBFT.

But it needs additional investigation, https://eips.ethereum.org/EIPS/eip-4895 also may be related.

**Comment by AnnaShaleva** [comment]
According to the post-merge Beacon consensus code, `WithdrawalsHash` block field is also affected by Shanghai:
https://github.com/bane-labs/go-ethereum/blob/df01fe2a6746bbb2b61238954ed3aeb626ea3342/consensus/beacon/consensus.go#L265-L271
