### ISSUE TITLE
dBFT stage 4: integrate voting

### ISSUE THREAD

**Issue by roman-khimov** [bane-labs/go-ethereum#14]
Header chain should be verifiable on its own, but we don't want to include the set of not-often-changed keys into every block, so:
 * allow for a key list to be included into `extra` as well, but only use it when `nextConsensus` differs from the current set
 * it should be included into the genesis block
 * once it's in the header, take them, verify they equal the `nextConsensus` hash and use to verify the next block
 * CNs should get the list from the voting contract once it's ready

**Comment by AnnaShaleva** [comment]
After #28 I have two reminders that should be carefully handled:

* `WithGetValidators` dBFT callback must sort validators, because primary calculation relies on this. Currently it's just the list of accounts taken from snapshot, so we need to ensure that they are properly sorted.
* `WithGetValidators` callback must return two separate lists of validators depending on the `txs` argument presence on the dBFT epoch bounds. We should be careful while implementing validators calculations for this callback, the same logic with `NextBlokValidators` and `NewEpochNextBlockValidators` from https://github.com/nspcc-dev/neo-go/pull/3110 may be implemented.

**Comment by roman-khimov** [comment]
Also adjust [eth/protocols/dbft/ledger.go](https://github.com/bane-labs/go-ethereum/compare/8f32d59cee70e37e95b9b40e7089fb44e6126f36..6d6fd68af4a6b7d112c07eb4c29ea7a7b3a7b259#diff-db0285e0e60d5a696aee679c608b6bccc6e6e95da1912163bf3e303388715be7) to check for allowed dbft message senders.

**Comment by AnnaShaleva** [comment]
Ref. https://github.com/bane-labs/go-ethereum/pull/7/files#r1462195034, `getPhaseByHeight` and `getCurrentPhase` APIs of Governance contract need to be used for proper Validators/NextConsensus retrieval on the dBFT side.

**Comment by AnnaShaleva** [comment]
Need to pay special attention to the `lastBlockNextNextConsensus` field of DBFT engine initialisation. There might be some problems with state-dependend NextConsensus initialisation after forced node shutdown when node doesn't have complete state in its storage to compute NextConsensus field for the next block. Ref. https://github.com/bane-labs/go-ethereum/pull/121#discussion_r1475895142 and ref. #100.
