### ISSUE TITLE
Adjust governance contracts for DKG

### ISSUE THREAD

**Issue by roman-khimov** [bane-labs/go-ethereum#159]
# Rationale

Anti-MEV requires update to contracts to be implemented, candidates should exchange key material to be able to work with encrypted transactions, see #22.

**Comment by doubiliu** [comment]
The function of DKG will be implemented using a new contract, and then the governance contract will call this contract to check whether the key distribution is completed.

**Comment by doubiliu** [comment]
Regarding DKG, I think there is another problem: currently, the global public key is changed every epoch cycle, which may cause the decryption of transactions sent at the critical point of epoch switching to fail.

**Comment by doubiliu** [comment]
- The first improvement method: use an unchanged global public key
Each time the epoch switches, the global public key remains unchanged, but the shared private key is redistributed. In this way, users do not need to pay attention to changes in the global public key, and there will be no problem of decryption failure in related encrypted transactions. But the main thing to note is that if the consensus nodes related to the previous epoch have been removed after each epoch switch, these nodes do not need to meet the fault tolerance assumption of DBFT. Then there is the possibility that they will be corrupted and colluded at some point in the future.

- The second improvement method: use a global public key that is valid across periods
By adding a special random offset, the global public key can be valid in two adjacent epochs. In this way, even if the user uses the global public key of the previous round, it will not affect the decryption in the next round. However, it still needs to be noted that after the last round of consensus was removed, there is still a certain possibility of corruption.

**Comment by doubiliu** [comment]
We may need to make a choice
1) In each new consensus cycle epoch, the DKG process is redone to generate a new global public key.
Benefits: The encrypted public key is completely isolated, and there is no possibility of old consensus nodes leaking secrets.
Disadvantages: For transactions that occur near the epoch switching time of the old and new consensus cycles, there is a possibility of decryption failure, and users need to pay additional fees.
2) Use an immutable global public key
Benefits: No matter how the consensus cycle epoch switches, the encryption public key remains unchanged and will not cause decryption failure.
Disadvantages: After the old consensus node loses the election, there is the possibility of joint evil and may decrypt transactions in advance.
3) Use a global public key with a life cycle of 2epoch
Benefits: Regardless of adjacent epoch switching, the encryption public key changes, but it does not affect decryption.
Disadvantages: After losing the election in the previous round of consensus nodes, there is the possibility of joint evil and may decrypt transactions in advance.

I will upload the technical details later

**Comment by doubiliu** [comment]
We introduce a new protocol:**Resharing protocol**
**Preparation Phase**
- Each participant in the last round of epoch needs to generate a random offset $\delta$, and its encrypted value $\Delta=\delta G_1$
- In the last round of epoch, each participant will uniformly add the random offset to the non-constant part of the previously submitted random polynomial. The random polynomial $f(x)=a_0+(a_1+\delta)*x+....( a_{t-1}+\delta)*x^{t-1}$, its random parameters $a=\{a_0,(a_1+\delta),..........,(a_{ t-1}+\delta)\}$
Generate $A=\{A_0=a_0G_1,A_1=(a_1+\delta)G_1,.........,A_{t-1}=(a_{t-1}+\delta) G_1\}$
- Each participant generates a random number r, and generates $R_1=rG_1, R_2=rG_2$ through G1 and G2 respectively.
- Recalculate **shared private key**$f:\{f(1),f(2),..........,f(n)\}$
- Recalculate **shared public key**$F: \{F_1=f(1)G_1,F_2=f(2)G_1,.........,F_n=f(n)G_1\ }$
- Use the public key of the next round participant to encrypt the shared private key corresponding to its number $E(f)=\{E(f(1)),E(f(2)),... ....,E(f(n))\}$
- Announce $PVSS =[R_1.R_2,A,F,E(f),\Delta]$
When all participants have released PVSS, the preparation phase ends

**Verification Phase**
All participants in this round received $PVSS =[R_1.R_2,A,F,E(f),\Delta]$
- Verify the equivalence of shared public keys F and A, $F_i=A_0+A_1*i+....A_{t-1}*i^{t-1},i\in(0,n]$
- Verify the equivalence between previous A and current A, $A_i=A_{i_{init}}+\Delta,i\in(0,n]$
- Use bilinear mapping to verify the equivalence of random numbers R1 and R2, $e(R_1,G_2)=e(G_1,R_2)$
- Each participant i uses the private key $dk_i$ to decrypt the corresponding $E(f(i))$ to obtain the corresponding shared private key $f(i)$
- Use bilinear mapping to verify Pedersen's commitment, $e(R_1f(i),G_2)=e(F_i,R_2)$
When the PVSS submitted by each participant passes the verification, the resharing process ends.
At this time, since the constant term of the random polynomial generated by each participant remains unchanged, $A_{0i}$ of each $PVSS_i$ is taken to form the **global public key**$S=A_{01}+A_{02 }+...+A_{0n}$ will not change either.

If you are worried that the new randomness is provided by the nodes in the previous round and the new nodes in this round do not participate, you can execute the protocol once by the nodes in this round.

With this protocol, it is possible to construct an unchanging global public key.

**Comment by doubiliu** [comment]
**Global public key across cycles**
we need do some modifications to the resharing protocol
Each participant is required to add a random to each term of the previously submitted random polynomial. Constant terms and non-constant terms are required to use independent random biases. The random polynomial $f(x)=(a_0+\phi)+ (a_1+\delta)*x+....(a_{t-1}+\delta)*x^{t-1}$, its random parameters $a=\{(a_0+\phi),(a_1+\delta ),..........,(a_{t-1}+\delta)\}$
Therefore, there is an inherent inclusion relationship between the global public key of each cycle and the global public key of the previous cycle $S'=S+\phi$
At this time, if the user uses the global public key discussed above for encryption, according to the equation of encryption and decryption
$M'=(M+rPubKey)-rG(PrivateKey')=M+rPubKey-rPubKey'=M+r(a_0+b_0+c_0)G-(a_0+b_0+c_0+\phi_1+\phi_2+\phi_3)G= -(\phi_1+\phi_2+\phi_3)G$
The calculated value will be one set of offsets $-(\phi_1+\phi_2+\phi_3)G$ less than the correct value
Additional calculations are needed in this round to make up for it.

**Comment by vncoelho** [comment]
> 1. n each new consensus cycle epoch, the DKG process is redone to generate a new global public key.
>        Benefits: The encrypted public key is comp

@doubliu, I just see option **1.** as a possibility, 
The other two (**2.** and **3.**) have a quite bad disadvantage.

I did not fully understand why the global public key changes every epoch. Do this happen even if the set of validators is the same?

**Comment by doubiliu** [comment]
> > 1. n each new consensus cycle epoch, the DKG process is redone to generate a new global public key.
> >    Benefits: The encrypted public key is comp
> 
> @doubliu, I just see option **1.** as a possibility, The other two (**2.** and **3.**) have a quite bad disadvantage.
> 
> I did not fully understand why the global public key changes every epoch. Do this happen even if the set of validators is the same?

Because each switch will regenerate a new shared private key. This needs to be checked when the governance vote is completed

**Comment by AnnaShaleva** [comment]
>The function of DKG will be implemented using a new contract

This is an incompatible change and to properly run T4 or mainnet we need at least a DKG contract stub to be deployed in the genesis block, because otherwise we'll need to implement a new hard-fork logic for this contract to be deployed.

> We may need to make a choice

I don't quite like the option 1, although it looks like an easiest way to implement. This option doesn't look good from the user's side, it will badly affect the user's experience if public key will be changed every dBFT epoch (every week in fact). We may introduce some threshold value to prevent users from sending the encrypted transactions several blocks before the dBFT epoch transition, but it sounds like a kludge to me.

Options 2 looks better, but I don't quite like the part with `may decrypt transactions in advance`. @doubiliu, what do you think about combining options 1 and 2, i.e. the following path: in real network consensus members don't change every epoch. We may use an immutable global public key for several subsequent dBFT epochs in a raw (when consensus list remains unchanged). And once new consensus members are elected, we may run the DKG process one more time for new consensus members to generate the new global public key. This new key will be immutable until the next validators list update. But this requires a delayed consensus list update (an additional phase after new consensus nodes will successfully finish DKG, and during this phase an old CNs will drive the network with the old immutable public key).

With this way of keys maintenance there still will be a very short period when new validators won't be able to decrypt the transactions submitted in the end of the previous epoch. But since validator list isn't updated every dBFT epoch, this period will be very rear.

**Comment by vncoelho** [comment]
I think that we should not change the DKG keys if the set of validators is not changed in a given epoch.
Keys should only change if any member request it or the set of members is changed.

I think that we could limit the number of new members to `f/2` in some period (let's say 3-4 epochs).
During these time, the remaining `3f +1 - f/2`members can still decrypt.
Meanwhile, the new DKG global public is already available.

**Comment by doubiliu** [comment]
> > The function of DKG will be implemented using a new contract
> 
> This is an incompatible change and to properly run T4 or mainnet we need at least a DKG contract stub to be deployed in the genesis block, because otherwise we'll need to implement a new hard-fork logic for this contract to be deployed.
> 
> > We may need to make a choice
> 
> I don't quite like the option 1, although it looks like an easiest way to implement. This option doesn't look good from the user's side, it will badly affect the user's experience if public key will be changed every dBFT epoch (every week in fact). We may introduce some threshold value to prevent users from sending the encrypted transactions several blocks before the dBFT epoch transition, but it sounds like a kludge to me.
> 
> Options 2 looks better, but I don't quite like the part with `may decrypt transactions in advance`. @doubiliu, what do you think about combining options 1 and 2, i.e. the following path: in real network consensus members don't change every epoch. We may use an immutable global public key for several subsequent dBFT epochs in a raw (when consensus list remains unchanged). And once new consensus members are elected, we may run the DKG process one more time for new consensus members to generate the new global public key. This new key will be immutable until the next validators list update. But this requires a delayed consensus list update (an additional phase after new consensus nodes will successfully finish DKG, and during this phase an old CNs will drive the network with the old immutable public key).
> 
> With this way of keys maintenance there still will be a very short period when new validators won't be able to decrypt the transactions submitted in the end of the previous epoch. But since validator list isn't updated every dBFT epoch, this period will be very rear.

1. Regarding compatibility, it may indeed require a hard fork.
2. I personally prefer option 3. There are several reasons:
   1) The premise of DBFT or Byzantine assumption is that 2/3 of the current consensus nodes are operating normally. This does not mean that the consensus nodes that have resigned will continue to fulfill their honest obligations. These outgoing consensus nodes may themselves retain fragments of the shared private key, which is a security risk. Option 2 uses an immutable global public key, which is both its advantage and disadvantage. If option 2 is used, from the user's perspective, they do not need to consider the issue of global public key changes, but there is a risk of early decryption of encrypted transactions. This is very contradictory. From a security perspective, Option 1>Option 3>Option 2.
    2) Although the consensus list will not change all the time, it is undeniable that it has the possibility of change. From this perspective, Option 1 is indeed unfriendly to users. If the user send a transaction near the epoch switching time, the transaction will fail to be decrypted, and the user will need to pay additional fees to resend the transaction. This problem does not occur in In Option 2 and Option 3, because the life cycle of the global public key in these two schemes is greater than 1 epoch.
    3) Option 3 is actually a variant of Option 2. Because if an encrypted transaction is not decrypted successfully for 2 epochs, the transaction itself should have expired. And more than 2 epoch, even malicious old consensus nodes cannot decipher encrypted transactions.

In addition, regarding the execution process of DKG, my thoughts are:
In the initial state, the initial consensus node uses DKG for key distribution. After that, each time a new candidate node list is generated and before formal work, let it execute the resharing protocol and execute it twice. This needs to be done using a contract and will not be included in the consensus process. Of course, if the new candidate node list is the same as the old node list, you can also directly execute the resharing protocol of option 2. At this time, the global public key will not change.

I also need to explain why the resharing protocol needs to be executed twice, because in principle, the random offset added in this protocol comes from the consensus nodes of the previous round. Theoretically, the previous round of consensus nodes can also retain this random bias. If executed twice, the new consensus node can add its own random offset to it, which is safer.

**Comment by doubiliu** [comment]
> I think that we should not change the DKG keys if the set of validators is not changed in a given epoch. Keys should only change if any member request it or the set of members is changed.
> 
> I think that we could limit the number of new members to `f/2` in some period (let's say 3-4 epochs). During these time, the remaining `3f +1 - f/2`members can still decrypt. Meanwhile, the new DKG global public is already available.

This is possible only through options 2 and 3. The global public key of options 1 cannot decrypt transactions across cycles.

**Comment by vncoelho** [comment]
Perfect, @doubiliu

I think that this is great:

> In addition, regarding the execution process of DKG, my thoughts are:
In the initial state, the initial consensus node uses DKG for key distribution. After that, each time a new candidate node list is generated and before formal work, let it execute the resharing protocol and execute it twice. This needs to be done using a contract and will not be included in the consensus process. Of course, if the new candidate node list is the same as the old node list, you can also directly execute the resharing protocol of option 2. At this time, the global public key will not change.

Also, the duration of 2 epochs is good.

In addition, if possible, just set a limit of a maximum change of `f/2`consensus nodes in 2 epochs as well.

**Comment by doubiliu** [comment]
> Perfect, @doubiliu
> 
> I think that this is great:
> 
> > In addition, regarding the execution process of DKG, my thoughts are:
> > In the initial state, the initial consensus node uses DKG for key distribution. After that, each time a new candidate node list is generated and before formal work, let it execute the resharing protocol and execute it twice. This needs to be done using a contract and will not be included in the consensus process. Of course, if the new candidate node list is the same as the old node list, you can also directly execute the resharing protocol of option 2. At this time, the global public key will not change.
> 
> Also, the duration of 2 epochs is good.
> 
> In addition, if possible, just set a limit of a maximum change of `f/2`consensus nodes in 2 epochs as well.

This is a voting restriction and should be included in the governance contract.

**Comment by vncoelho** [comment]
> > Perfect, @doubiliu
> > I think that this is great:
> > > In addition, regarding the execution process of DKG, my thoughts are:
> > > In the initial state, the initial consensus node uses DKG for key distribution. After that, each time a new candidate node list is generated and before formal work, let it execute the resharing protocol and execute it twice. This needs to be done using a contract and will not be included in the consensus process. Of course, if the new candidate node list is the same as the old node list, you can also directly execute the resharing protocol of option 2. At this time, the global public key will not change.
> > 
> > 
> > Also, the duration of 2 epochs is good.
> > In addition, if possible, just set a limit of a maximum change of `f/2`consensus nodes in 2 epochs as well.
> 
> This is a voting restriction and should be included in the governance contract.

These limits also exists in other protocols as far as I remember.
That is true, it is for the governance contract.

**Comment by doubiliu** [comment]
In fact, the simplest summary of the resharing protocol is a shuffle. The old shareholders mix their cards and deal them again to the new shareholders. The cards in the hands of the old and new shareholders are the same when combined.

**Comment by doubiliu** [comment]
> > The function of DKG will be implemented using a new contract
> 
> This is an incompatible change and to properly run T4 or mainnet we need at least a DKG contract stub to be deployed in the genesis block, because otherwise we'll need to implement a new hard-fork logic for this contract to be deployed.
> 
> > We may need to make a choice
> 
> I don't quite like the option 1, although it looks like an easiest way to implement. This option doesn't look good from the user's side, it will badly affect the user's experience if public key will be changed every dBFT epoch (every week in fact). We may introduce some threshold value to prevent users from sending the encrypted transactions several blocks before the dBFT epoch transition, but it sounds like a kludge to me.
> 
> Options 2 looks better, but I don't quite like the part with `may decrypt transactions in advance`. @doubiliu, what do you think about combining options 1 and 2, i.e. the following path: in real network consensus members don't change every epoch. We may use an immutable global public key for several subsequent dBFT epochs in a raw (when consensus list remains unchanged). And once new consensus members are elected, we may run the DKG process one more time for new consensus members to generate the new global public key. This new key will be immutable until the next validators list update. But this requires a delayed consensus list update (an additional phase after new consensus nodes will successfully finish DKG, and during this phase an old CNs will drive the network with the old immutable public key).
> 
> With this way of keys maintenance there still will be a very short period when new validators won't be able to decrypt the transactions submitted in the end of the previous epoch. But since validator list isn't updated every dBFT epoch, this period will be very rear.

I would like to add something about the execution process location of DKG. Because of our current voting mode and settlement method, if we switch the consensus according to the existing logic , the time left for these selected nodes to execute DKG will be very short. It is better to change it to a pipeline method.

**Comment by roman-khimov** [comment]
> I think that we should not change the DKG keys if the set of validators is not changed in a given epoch.
Keys should only change if any member request it or the set of members is changed

Agree with that.

> I think that we could limit the number of new members to f/2 in some period (let's say 3-4 epochs).

There is a similar (although more strict, only 1/3 is updated at time) mechanism in NeoFS for alphabet node synchronization between mainnet and sidechain (changing all of them at once is too risky): https://github.com/nspcc-dev/neofs-node/blob/e5da07298bbe032d0df3f9e2eb1cd47b31592442/pkg/innerring/processors/governance/list.go#L17

But I don't think it's needed here. What we can do is:
 * _nothing_ if the list doesn't change, resharing is not required
 * generating a new public key _and_ resharing pieces of the old one otherwise, the old key is valid for one more epoch this way (and gone after that), but new transactions should use the new one.

This way we'd still change keys from time to time, but old ones would be available for one more epoch.
