### ISSUE TITLE
GVN-01 - High Resource Consumption in candidateList `[High]`

### ISSUE THREAD

**Issue by shargon** [bane-labs/go-ethereum#197]
<p>A critical vulnerability related to excessive resource consumption has been identified in the <code>onPersist </code>method of the <strong>NeoX</strong> <code>Governance</code> contract, which uses the <code>EnumerableSet</code> library. Specifically, the <code>values()</code> method of this library is called multiple times: directly on line 313 and via the <code>_computeConsensus()</code> function on line 325. This method is known for its high gas demand, as it copies all values of the <code>candidateList</code> set in memory, which is described in the OpenZeppelin documentation as potentially expensive.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/5fff8a15-81e5-4c7a-815e-5876d3f3472a)

<p>The main concern is that repeatedly using <code>values()</code> in a method that alters the state of the contract increases the gas cost significantly, especially as the <code>candidateList</code> set grows. This increase in gas consumption not only increases operating costs, but also represents a serious security vulnerability.</p>

![image](https://github.com/bane-labs/go-ethereum/assets/3167973/96eb495a-ecfe-416e-8289-c62278aee98a)

<p>Since the registration of new candidates in <code>candidateList</code> is public, an attacker could exploit this feature to register a large number of candidates, causing the execution of <code>onPersist</code> to consume more resources than can be provided in a block, effectively blocking the function and causing a denial of service (DoS).</p>

**Remediation:**
<ul><li><p>Limit the use of <code>values()</code> in critical functions: Redesign the <code>onPersist</code> method to eliminate repeated use of the <code>values()</code> method within operations that change the state of the contract. Consider using iterators or alternative mechanisms that do not require copying the entire set into memory.</p></li><li><p>Perform load testing and contract optimization to ensure that key functions can handle a high number of interactions without exceeding resource limits. These tests will help identify and mitigate potential failure points due to excessive gas consumption.</p></li></ul>

**References:**
- https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/structs/EnumerableSet.sol#L211-L218

**Source references:**
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L313">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L313</a></p>
<p><a target="_blank" rel="noopener noreferrer nofollow" href="https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L325">https://github.com/bane-labs/go-ethereum/blob/ca856ce0ad5d20490d8e7304430f4db3e6331340/contracts/solidity/Governance.sol#L325</a></p>

**Comment by roman-khimov** [comment]
onPersist is very special and this call is limited to `30_000_000` gas:
https://github.com/bane-labs/go-ethereum/blob/7d8b639c7f0de170f5f009cca7599f5dafda87e7/core/state_processor.go#L217

If it fails, we're in BIG trouble, all nodes would just stop (and we've seen that in tests, right, @nicolegys?). So it MUST NOT fail. Ideally, it should always use some static known amount of gas irrespective of the state.

Really important thing to fix.

**Comment by txhsl** [comment]
The repeated use of `values()` will be removed along with #201. But it is not the operation with the highest cost, because the following `_computeConsensus()` takes more, may be 20 times higher.

We've used a top K algorithm to save gas, but `OnPersist()` still takes up to 36,000 gas to handle the list with 20 candidates, when it is going to update the CN list (once per week on T3). With an approximately linear evaluation, it requires about 2100 candidates to hit the current gas limit `30_000_000`. With a 1000 GAS register fee cost per address, it takes `2_100_000` GAS to perform this kind of attack.

The sort happens in VM memory is necessary, otherwise we will have to maintain a dynamic list and leave it to voters to pay for. The good news is that we are not calling `OnPersist()` with a direct transaction but a customized VM invocation, so it will not be included in the block gas limit or affect the traffic, also, the gas limit is configurable. I think we can avoid it by improving the `vmenv.Call()` settings, what is your opinion?

**Comment by roman-khimov** [comment]
Gas limit can be raised, true. Maybe we should also limit the number of candidates then. 2K is not a small number for this kind of thing, but we better stop accepting new candidates when we know it can cause problems with `onPersist`. Then the gas limit can be adjusted, then the candidate limit can be raised (if needed).
