### ISSUE TITLE
Import an anti-MEV feature based on threshold decryption

### ISSUE THREAD

**Issue by txhsl** [bane-labs/go-ethereum#22]
# Rationale

Recently, we are doing some researches on MEV (Miner Extractable Value) in DBFT. In Ethereum, for example, MEV is some potential value that miners/validators can earn by changing the transaction sequence in his block. For an Uniswap transaction, users always set a max/min amount limit for their input/output because of slippage. But miners/validators can listen and add another two transactions to force the user to deal at the limit, and take the slippage as earning. The economics about MEV is quite complicated, and the case I mentioned above is just one of existing MEV methods. 

In DBFT, MEV is an untouched area. Our consensus committee has a decisive power in validator MEV, but never used. So we have an plan to import some anti-MEV feature to Bane's DBFT, which is to set up an encrypted area in each block and only expose these transaction scripts after they are sequenced. 

# Implementation

Inspired by Radius (https://github.com/radiusxyz) and BLS consensus (https://github.com/neo-project/neo-modules/issues/637), we have a similar idea called Delayed Threshold Decryption. For example, in each round of DBFT, we can generate a public key and several pieces of a secret key based on a Decentralized Key Generation (DKG). The public key is exposed to everyone so that users can use it to encrypt their transactions before the next round of DBFT. When the next round comes, our consensus committee expose all pieces of the threshold secret key (or just share some partially decrypted information), decrypt and execute these transactions just after the block header is accepted by consensus, when nobody knows the transaction contents. 

The decryption process is clear. In a 3-stage DBFT, validators propose and vote to a new block header. Validators will only share the secret when commit if the header is acknowledged. Then a Verifiable Delay Function (VDF) is realized. However, the DKG related part is still under investigation. 

Recently, we are reading some research papers about DKG and TE in blockchain, like [*Practical Asynchronous Distributed Key Generation*](https://ieeexplore.ieee.org/abstract/document/9833584/) and [*1-Round Distributed Key Generation with Efficient Reconstruction Using Decentralized CP-ABE*](https://ieeexplore.ieee.org/abstract/document/9715067). We will keep on updating our progress in this issue if we have, and if you have any other idea about MEV protocol, let's discuss it as well.

**Comment by txhsl** [comment]
This feature will help #12 as well.

**Comment by steven1227** [comment]
This one is related to the consensus module that @roman-khimov 's team is working on. We need your opinions

**Comment by AnnaShaleva** [comment]
We've discussed this topic on the meeting. @txhsl, thank you very much for the research, design and explanation!

> This feature will help https://github.com/bane-labs/go-ethereum/issues/12 as well.

We need to use BLS signature in https://github.com/bane-labs/go-ethereum/issues/12 due to the fact that validators signatures are a part of the block header and, which is more important, a part of the hashable block data in Eth chain. Thus, block's validators signatures must be a constant set of bytes so that the subsequent block's hash remains constant between different validators that accept this block. Thus, we use BLS to provide this ability (it allows to construct constant signature for multisigners).

Here are the main problems that need to be solved for this solution (extracted from the discussion):

1. >users can use it to encrypt their transactions before the next round of DBFT
   
   The presented solution roughly restricts the transaction lifetime. If the transaction won't be accepted before the next dBFT round, then it needs to be invalidated, because everyone will know the decription keys by this moment. The user then has to compose new transaction and relay it, whereas in Neo or Eth networks the transaction lifetime can leave in pool for quite a large time before it's accepted to the block.

2. > In a 3-stage DBFT, validators propose and vote to a new block header.

   Eth blocks include state root in the block header. State root is calculated based on the state got from the transactions of the currently processed blocks. Thus, to propose and vote for a new block, validators have to be avare of transaction execution scripts to be able to calculate stateroot. It can't be reached for the proposed scheme, because transaction scripts are encripted.

3. > in each round of DBFT, we can generate a public key and several pieces of a secret key

   The generation procedure assumes that each validator is available at the moment of generation. And here are two problems:
   * Validator node can be out of the network. While dBFT is able to function normally with M out of N nodes alive, the current solution requires *all* nodes to be presented in the network, thus it's a point of centralisation.
   * Validators list may change at any time (consider re-voting procedure and the updated list of validators).
   
4. Not actually a problem, but an idea that was also discussed earlier for the Neo chain: Neo and dBFT-based Geth is able to escape the MEV problem by changing committee members list: just exclude the malicious validator via re-voting.

**Comment by doubiliu** [comment]
Hei guys.I have prepared a more detailed plan. Welcome to discuss together.
[MEV resistance mechanism.pdf](https://github.com/bane-labs/go-ethereum/files/12878283/MEV.resistance.mechanism.pdf)

**Comment by AnnaShaleva** [comment]
@doubiliu, @txhsl, thank you for the detailed proposal! I've read this plan and still couldn't find the answer for a couple of questions mentioned above. Could you, please, give more detailed answer to these questions? (A part of them are migrated from the https://github.com/bane-labs/go-ethereum/issues/22#issuecomment-1739237701). 

The first one is the question about state root in header.
> When in the third phase of consensus, each consensus node needs to include the decryption fragments required for threshold
decryption in their own commit, collect decryption fragments sent by other consensus nodes, aggregate them into a complete decryption key, and append it to the block.

All anti-MEV transactions affect the storage state. As described in the citation, the participants performs the decryption fragments exchange at the commit stage. But the primary node has to propose state root of the current block in the prepare request stage which is impossible for the described scheme as the scripts of anti-MEV transactions are encrypted by the moment of PrepareRequest. At the same time, we can't just exclude the invocation results of anti-MEV transactions from the block's state root as it will break a set of other processes in the blockchain.

The second question is about preparation and validation phases of the DKG process. Is it true that threshold encryption and decryption will properly work with threshold `t` set to the dBFT honest nodes count (M) and when the rest of nodes (N-M) behave maliciously? In the Preparation  and Verification Phase of DKG process there's a set of steps that requires data from all (N) nodes, and with dBFT we may have only M nodes alive. What happens with these steps in this case?

The third question is related to the following citation:

> Before the next round of consensus node list takes effect, it is necessary to query the DKG contract to
check if the DKG process for that round has been completed. If the DKG process for the current round cannot be completed, the consensus node list from the previous round will continue to be used.

Imagine that DKG process wasn't completed for the last round (one of the nodes was out of the network) and we are continuing to use the consensus list from previous round for DKG process. Imagine that the list of validators has been changed in the current round and it doesn't match the list that DKG process uses. What happens next? What happens if the DKG process can't be completed several times in a raw for a subsequent set of dBFT rounds?

The last question connected with the following citation:

> aggregate them into a complete decryption key, and append it to the block.

Consensus nodes are attaching their decryption fragments to the block in the commit stage and the block is broadcasted to the network. The question is what is the place in the block where decryption keys are placed to? Geth blocks are hashable, and (unlike the Neo blocks) the resulting block's signatures are hashable as far (that's why we've proposed to use BLS signature for consensus nodes for #12), thus even block's signatures should be hashed to some constant value. Here with the described DKG process we have one more additional block field (?) that should also be hashable, but its value can be properly set only after all (or at least M out of N) commits are accepted.

Another concern connected with this question was that we're trying not to modify the block structure so that existing Eth-related tools (that are familiar with Eth block structure) are still able to work with dBFT-authored blocks without any problems. Are the proposed decryption fragments attached to the block aligned wrt this statement?

And one more question that is not quite related to the proposal design. My thought was that our current goal is to concentrate onto minimum working prototype of Geth node with bridge, dBFT and governance that can be run and tested in testnet by the date mentioned by @steven1227. After that we'd probably like to release some alpha version and try it on mainnet. And after that, when we have a stable working prototype, we may think about adding some features like the proposed anti-MEV solution to it. I'm not against this feature, I just want to say that it is not the most critical thing that affects or blocks the project at the current stage; and there are still a couple of issues that are not clear to me and it's not clear how they can be applied to the combination of dBFT-based model of consensus and Eth-based model of blocks.

Thank you for considering my questions and thoughts!

**Comment by doubiliu** [comment]
@AnnaShaleva 
Good question! Let me explain:

**The first question： stateroot calculation**
The calculation logic of stateroot between Ethereum and neo is indeed different, but I think this is not a big problem. In the past, we proposed the concept of replacement in neo's issue. We can use the previous block ‘s data in the storage area as stateroot and stuff it into the current proposal block.

**The second and third questions: DBFT evil**
It should be noted here that the DKG process and threshold encryption and decryption are two steps. The DKG process requires 100% honesty. Encryption and decryption only need to reach the threshold value t to work normally.
Although the DKG process requires 100% honesty, it does not need to happen for every block. Because consensus changes now use a proposal system, the DKG process can be completely independent of the consensus stage, and voters can propose a list of DKG nodes in advance, and then check whether these lists have completed the DKG process during voting.

**The last question: additional keys**
This decryption key does not need to be added to the inside of the block, but can be used as a plug-in for the block. It can exist in separate areas, with separate validations. If you are worried about being tampered with during delivery, you can add an additional signature. This is somewhat similar to the stateroot principle of neo plug-in, because neo's stateroot is not added to the block.

About work process
This plan is mainly to refer to everyone's opinions and see if there are any flaws and shortcomings. Some of the work in this plan can actually be developed independently of the consensus and will not affect existing things.

**Comment by txhsl** [comment]
As a complementarity to @doubiliu, I have to give some more comments.

First, the scheme described in the document is mainly consisted of 2 steps. The first step happens during the governance vote. A governance change now needs an extra DKG to be acknowledged, and this DKG requires 100% honest participation from all validators. The first step generates a group of keypairs that can be used for a long period of consensus (until the governance changes again). Then, the second step happens after commitment, validators expose the transaction secrets, and this requires a `t` threshold, e.g. 2/3. So the consensus still keeps the feature of fault tolerance. And this separated DKG process also allows a long lifetime of transactions. Txs are able to lie in the mempool, because we will not change the keys after every block.

Second, I'm sorry to say, but the state root thing has to be like so. We encrypt the txs so that their content can not be analysed before they are sequenced. It determines that the global state can not be computed before decryption. But as @doubiliu said, this DKG and TE scheme needs time to be developed, independently at the beginning, so it is not conflict with our current goal of running Geth with dBFT-authored blocks without any problems. But anyway, we may have to make some modification in the future.

**Comment by steven1227** [comment]
Hey @AnnaShaleva , Sure, I totally agree with you on this. A stable working solution is the highest priority for the first alpha version. Let us do some more POC and independent work first.

**Comment by txhsl** [comment]
The POC is almost done here, https://github.com/txhsl/tpke, including a DKG and a threshold encryption as described in our document. Some further coding is undergoing to make it better.

**Comment by roman-khimov** [comment]
I'd like to keep the main discussion here, so we've looked at `neo_sidechain_against_mev_protocol_docs7.pdf` and while it's much more viable than previous concepts with have some comments and suggestions for it.

### Consensus mechanism
> Stage 1, phase 1
> Check if each sender has enough gas. Deduce the encryption fees, or drop the transaction if
> the sender has no enough gas.

How are you going to do that if transactions are not yet included into a block? Which relates to the third phase below.

> Stage 1, phases 2-3

Once we're past phase 2 everyone on the network knows encrypted transactions, but we don't yet have a block. We need to evaluate the consequences of this.

> Stage 1, phase 3

Once PreBlock is generated, how will it be relayed to the rest of network nodes? What happens on simultaneous CN nodes reboot? They can easily lose the state of accepted PreBlock, because unlike the usual Eth block, PreBlock isn't stored in
the blockchain.

> stage 1, phase 3:
> If decryption fails, drop the transaction
> Recover the sender's public key of the unencrypted transaction. If it's different from the sender of the encrypted transaction, drop the transaction

What prevents spamming the network with incorrectly signed transactions then? Phase 1 doesn't guarantee payment.

The requirement of the same encrypted/decrypted transaction sender can also significantly affect encrypted transactions applicability to different scenarios. Knowing the sender is already something in many cases. Below we provide the scheme where it's possible to have different encrypted/decrypted transaction sender.

> stage 1, phase 3:
> Generate the PreBlock , including a mixture of encrypted transactions and ordinary ones

While ordering is protected from manipulation by stage 2 constraints, we can have a view change in dBFT and it's not obvious how it could relate to these transactions that are currently completely known. This is especially
concerning if we're considering stages as two more or less independent dBFT processes. Stage 1 can be successful, but what are the guarantees of stage 2 picking up stage 1 results? What if stage 2 can't proceed with the proposed
set of transactions? Ordinary dBFT would change view and retry with some new set of transactions proposed by a different primary, we can't forbid changing the primary for liveness reasons, but:
 * if the new primary is obliged to follow the PreBlock, we can have a deadlock if the PreBlock is wrong for any reason
 * if the new primary can change transactions, then it knows the contents of encrypted ones and can affect the resulting block

> stage 2:
> Now that all the transactions in the PreBlock can be decrypted, we can, based on the PreBlock,
> run another round of ordinary dBFT

This scheme significantly increases overall block acceptance time. With this scheme it's required two dBFT rounds for block acceptance, and both rounds may face ChangeViews.

### DKG process

> In practice, the private and public keys are managed by a contract, and are frequently changed.
> The contract has the following methods

The voting scheme proposed relies on "batched" voting. i.e. relies on the fact that there's a set of proposals where one proposal contains N candidate nodes addresses. In this scheme the most voted proposal wins, but:
 * such "batched" scheme is not competitive with the voting mechanism that we have in N3 where people can give their vote to a separate candidate and the top N candidates win.
 * such "batched" scheme makes it harder for new non-standby-related candidates to enter the game and to get their place in the resulting set of nodes
 * if the proposal mechanism will be implemented similar to the currently implemented in https://github.com/bane-labs/go-ethereum/pull/7 Governance scheme, then the proposal's author can be only Validator/previously elected node which is also bad for newcomers candidates.
 * there should be a lot of proposals registered to cover all possible combinations of the candidates nodes.

This question is related to governance discussion, of course.

### Enhancement proposal for DKG process

> All users elect consensus candidates with their GAS
> New keys take effect when CheckDKGProposalFinished passes, and block number reaches
> validHeight

This can be simplified with some key exchange phase for the governance. The key exchange has to be done by exactly the voted members, so it's important to have some stable set of members first which can be done via a regular (non-batched) voting which ends as the epoch ends and then we should have an additional phase (maybe a day) where elected nodes would exchange their keys via a contract and validators would be switched once we have enough keys (or this set expires and we punish nodes that failed to add their keys).

### Enhancement proposal for encrypted transactions

We can simplify the overall scheme if we're to move encrypted transactions to the next block. Their encrypted counterparts (just messages with some fees) can be included into a block with the decryption keys in Extra. Then the next
prepareRequest will be obliged to include unencrypted transactions from the previous one. This isn't exactly HFT-friendly, you're delayed by a block, but:
 * some fee will inevitably be paid, envelope transactions are explicit, it's easier to control these envelopes and sort based on envelope fee (irrespective of the payload fee)
 * there won't be any additional consensus rounds for a single block (don't forget, it's a delay for block creation)
 * once keys are exposed, transactions are ordered and commited to a block which is known to the whole network, they can't disappear (like PreBlock)
 * most of potential uses (exchanging hefty sums/unlocking some secrets) shouldn't be sensitive to a block delay
 * envelope transactions don't require their sender to be the same as attached encrypted transaction has, this broadens the potential application scope of encrypted transactions
 * there is more visibility into the process and it's easier to track both transactions

So the overall scheme is:
1. Introduce a special type of transaction ("Envelope" transactions). These transactions are allowed to have some Message payload included into transaction's data. In general case, this Message may contain anything that Envelope sender wants, but for this particular case Message should include encrypted transaction data to be properly handled by consensus. If Message contains some corrupted or irrelevant data, then Envelope won't have any side-effects at step 4 (which means Envelope's sender spends his funds for nothing).
2. Introduce special customizable fee for Envelope transactions. Envelope's sender should have enough balance to pay for Envelope transaction including special Envelope fees. At the same time, customizable Envelope fee should not depend on the decrypted Message content.
3. Relay, validate and include Envelope transactions into block X via standard dBFT process together with the rest of transactions and with decryption keys in Extra. Envelope transactions should have valid sender, should pass some basic transaction verification rules similar to other transactions. No special Message verification is being performed, since Message is just a side transaction's data.
4. During the next dBFT round for block X+1 during PrepareRequest creation and verification all CNs have to iterate through Envelope transactions of the previous block X. For every subsequent Envelope try to extract encrypted transaction from Envelope's Message. If failed, then go the next Envelope. If succeeded, then use decryption keys to get unencrypted transactions from the Envelope's Message content. Validate unencrypted transaction and if valid, then include into proposed PrepareRequest for block X+1 preserving the order corresponding to Envelopes' order. Simple transactions may also be included in the same block if there's a place for it. Follow the standard dBFT rules and accept block X+1. CVs are allowed.
5. Validation rules for unencrypted transactions should follow the simple transaction validation rules. It's not necessary for unencrypted transaction to have the same sender as Envelope has.

Also, the following idea may be considered: don't create a separate tx pool for Envelope transactions since Envelope obeys standard transaction verification rules (except for an additional required fee). Unencrypted transactions got from Envelopes are not being included into standard tx mempool, but during the resulting block X+1  verification can be guaranteed to have larger priority than simple transactions proposed via mempool mechanism.

**Comment by txhsl** [comment]
### About DBFT

> How are you going to do that if transactions are not yet included into a block? Which relates to the third phase below.

Users here will first send a normal legacy transaction to commit his secret transaction within the `data` field, so the wrapper can be used to charge a decryption fee. We can specify a `impossible` address as `to` and charge the fee through `amount`. The decryption fee is only based on the `data` and its size, no matter what secret is inside.

> Once we're past phase 2 everyone on the network knows encrypted transactions, but we don't yet have a block. We need to evaluate the consequences of this.

With a legacy transaction as carrier, we can include known transactions and generate a pre-block, so the tx sequence is decided at first. After that, CNs will try to perform decryption and build the final block.

> Once PreBlock is generated, how will it be relayed to the rest of network nodes? What happens on simultaneous CN nodes reboot? They can easily lose the state of accepted PreBlock, because unlike the usual Eth block, PreBlock isn't stored in
the blockchain.

PreBlock is just a message payload, so CNs can recover from others, unless the whole network breaks and nobody knows the PreBlock. But this case breaks the DBFT consumption.

> What prevents spamming the network with incorrectly signed transactions then? Phase 1 doesn't guarantee payment.

Phase 1 guarantees the payment of decryption, IMO, users can spam the network with some incorrectly signed transactions, they pay for the decryption, but after we decrypt the envelope, we can drop it.

> The requirement of the same encrypted/decrypted transaction sender can also significantly affect encrypted transactions applicability to different scenarios.

Yep, it is a problem, we already have a simple demo, I will mention it in the end. If we require legal and signed Ethereum transactions in envelopes, then all things can be secret, and I think we can, the cost is data size.

> This scheme significantly increases overall block acceptance time. With this scheme it's required two dBFT rounds for block acceptance, and both rounds may face ChangeViews.

Yep, the whole process is like 2 rounds of DBFT, but the second one should only be proposed based on PreBlock, otherwise it is illegal. NeoResearch and we think there is no need to allow change view after PreBlock message is voted by 2f+1, because we don't even need a speaker after that.

We have implemented a simple 4-stage DBFT demo with threshold decryption and threshold signature for this proposal, please check it at https://github.com/txhsl/dbft-anti-mev when free.

**Comment by txhsl** [comment]
### About DKG

> The voting scheme proposed relies on "batched" voting. i.e. relies on the fact that there's a set of proposals where one proposal contains N candidate nodes addresses.

Yep, it's also a #7 related thing.

> This can be simplified with some key exchange phase for the governance. The key exchange has to be done by exactly the voted members, so it's important to have some stable set of members first which can be done via a regular (non-batched) voting which ends as the epoch ends and then we should have an additional phase (maybe a day) where elected nodes would exchange their keys via a contract and validators would be switched once we have enough keys (or this set expires and we punish nodes that failed to add their keys).

An additional phase suits in many scenarios, nice idea. But we are afraid of a case that if some of the voted members refuse to exchange their keys, maybe because they don't prefer the committee and don't want someone to participant.

**Comment by txhsl** [comment]
> Also, the following idea may be considered: don't create a separate tx pool for Envelope transactions since Envelope obeys standard transaction verification rules (except for an additional required fee). Unencrypted transactions got from Envelopes are not being included into standard tx mempool, but during the resulting block X+1 verification can be guaranteed to have larger priority than simple transactions proposed via mempool mechanism.

I'm evaluating the enhancement proposal for encrypted transactions, but we may still need a new tx pool for Envelope transactions, because an envelope needs some crypto verifications to confirm that after the user declares a valid randomness he provides a related commitment, so CNs can know that it is some other CNs send evil shares when the decryption of envelope fails, by verifying the commitment and decrypted things.

**Comment by AnnaShaleva** [comment]
> but we may still need a new tx pool for Envelope transactions

It was just a brief idea, and in general we're not against a separate envelope pool.

However, our primary concern is two-staged dBFT process. We'd like to avoid such dBFT modifications as much as possible, because such changes may seriously destabilize the consensus. At least for now we know that current dBFT version works in most cases, it's tested for a long time in N3 and it's tested with TLA+ model, so it's safe for us to rely on the existing consensus mechanism. And that's why we'd ask you to pay a special attention to the proposed enhancement for encrypted transactions. It doesn't adds any additional stages or middle stages to the consensus process, and in fact it doesn't require any dBFT/consensus modifications at all, so we kindly ask you to consider/evaluate this proposal.

**Comment by txhsl** [comment]
An additional DBFT stage or another DBFT block is a trade-off, there are some potential requirements,

- Anti-MEV transaction is paid with extra fee, so it should be listed at the beginning and executed first with a high priority, otherwise it might be `MEVed` by normal transactions in accident;
- We still want 1-block finality and equal respond time, but 2 rounds of DBFT will decrease the through put to half, and involve two speakers, which is not good if we want to generate random numbers from this randomness;
- We don't want to change Ethereum's block structure to store new things like decryption shares, or DKG shares, and they may disappear as well;

In the worst case, the whole network crashes and loses the PreBlock payload, the only risk is these envelopes' secrets can be exposed because of a potential decryption sharing, but the transaction itself will not disappear, so the safety remains.

@doubiliu and I have discussed 2-round DBFT and 4-stage DBFT through documents and meetings with @vncoelho, @vang1ong7ang, @steven1227 and so on, and choose the latter, so before we implement the enhancement, we can take these reasons into consideration and discuss more about it.

**Comment by roman-khimov** [comment]
> Phase 1 guarantees the payment of decryption, IMO, users can spam the network with some incorrectly signed transactions, they pay for the decryption, but after we decrypt the envelope, we can drop it.

I'm not sure how it works. Envelope tx needs to be accepted into a real block for this to happen, but what I see in the document it's thrown away after decryption.

>  there is no need to allow change view after PreBlock message is voted by 2f+1, because we don't even need a speaker after that

Makes the consensus much more fragile to me and diverts from an idea of two standard dBFT rounds requiring protocol modifications. Reaching agreement over `PreBlock` doesn't mean reaching agreement over the resulting block, there has to be a proposal with the final tx list and execution result, at least following the `based on the PreBlock,
run another round of ordinary dBFT` logic. What you're suggesting is more like replacing ordinary dBFT (two rounds) with a single round of exchange for final data, assuming that with a valid `PreBlock` everyone can calculate the resulting block independently. Like an additional "Commit" round.

> we are afraid of a case that if some of the voted members refuse to exchange their keys

It's very easy to track and act upon, they deposit some GAS and they update the key list, if there is no key in the contract by the deadline deposit (or a part of it) vanishes and member gets kicked out of the voting process, some new set of validators can start the key exchange then.

> We still want 1-block finality and equal respond time

Yeah, it's clear that you're designing the thing to fit encrypted transactions into the same exchange where the keys emerge, but this makes the process more fragile. A single block delay makes the process much more reliable and not requiring a lot of modifications (separate pool? not needed. dbft modifications? not needed), so the question to me is do we need to take more risk to satisfy this single-block finality?

**Comment by txhsl** [comment]
> I'm not sure how it works. Envelope tx needs to be accepted into a real block for this to happen, but what I see in the document it's thrown away after decryption.

No, the wrapper transactions are included as well. The doc says,

> PreBlock = List<EnvelopedTransaction | Transaction>
> Extract(PreBlock) = all EnvelopedTransactions in PreBlock + all valid decrypted EnvelopedTransactions in PreBlock + all Transacions in PreBlock

The PreBlock contains envelope carrier transactions and normal transaction to define the tx sequence, Then the consensus get the envelopes from their wrappers, decrypt them, and list them after carrier transactions but before normal transaction. These words could be confusing, but in the final block, we first execute envelope carriers to charge decryption fees, then execute decrypted envelopes and finally normal transactions. For this part, maybe just take a look at my demo.

> What you're suggesting is more like replacing ordinary dBFT (two rounds) with a single round of exchange for final data, assuming that with a valid PreBlock everyone can calculate the resulting block independently. Like an additional "Commit" round.

Yup, I regard this round as a second commit as well, or a logical reorg.

> It's very easy to track and act upon, they deposit some GAS and they update the key list, if there is no key in the contract by the deadline deposit (or a part of it) vanishes and member gets kicked out of the voting process, some new set of validators can start the key exchange then.

We are glad to see this change if possible, which means there are fewer DKGs to be performed.

> Yeah, it's clear that you're designing the thing to fit encrypted transactions into the same exchange where the keys emerge, but this makes the process more fragile. A single block delay makes the process much more reliable and not requiring a lot of modifications (separate pool? not needed. dbft modifications? not needed), so the question to me is do we need to take more risk to satisfy this single-block finality?

We can lock the view change when prepare responses get voted passed, to make it a bit easier. But for user, I mean, 1-block finality is attractive. Few people prefer to pay for 2-block finality when normal transactions are 1-block finality.

**Comment by vncoelho** [comment]
Decision making is just until Phase 3, the same as nowadays.
After tx ordering and decryption, which is concluded on phase 3, the rest is just informative. 
Just payloads aggregation among 2f+1. There is not even the need of a Speaker on "Phase 4".

In this sense, "one extra phase" will be enough.

**Comment by roman-khimov** [comment]
> Then the consensus get the envelopes from their wrappers, decrypt them, and list them after carrier transactions but before normal transaction.

OK, that explains many things.

This limits the number of encrypted transactions, btw, at least to a half of the block. GAS limit can also come to play, but looks like you've thought about it already (`gasLimit` is duplicated cleartext).

Still, my primary concern is dBFT modification that will be required for this. There is a big difference between running standard dBFT twice and modifying it. We can avoid it with delayed execution (as outlined above and I'd prefer it for simplicity) or we can try thinking in some different direction.

**Comment by roman-khimov** [comment]
Blocked by https://github.com/nspcc-dev/dbft/issues/112. This particular issue is limited to static key setup.

**Comment by doubiliu** [comment]
> Blocked by [nspcc-dev/dbft#112](https://github.com/nspcc-dev/dbft/issues/112). This particular issue is limited to static key setup.

We have prepared a demo and need to transplant it into a smart contract. In addition, I am wondering whether it is necessary to add the function of immutable global public key.
