### ISSUE TITLE
inaccurate words on voting's readme when consensusSize is even

### ISSUE THREAD

**Issue by dusmart** [bane-labs/go-ethereum#253]
https://github.com/bane-labs/go-ethereum/blob/0d638659ac8e223f5616c0c2f10c03e83f2569c1/contracts/README.md?plain=1#L41-L43

https://github.com/bane-labs/go-ethereum/blob/0d638659ac8e223f5616c0c2f10c03e83f2569c1/contracts/solidity/base/GovernanceVote.sol#L74

The actual logic is `more than or equal to` which is `not less than`. But the document says `more than`.

Although it doesn't matter under current settings where consensusSize is 7, it's better to make the document more accurate.

**Comment by dusmart** [comment]
Apart from changing the document. The other solution maybe changing the `votedCount >= (voters.length + 1) / 2;` to `votedCount > voters.length / 2;`.

So that it keeps the same behavior under current settings while it also met the `more than` requirement as stated in the document.

**Comment by AnnaShaleva** [comment]
It should be unified, and it's worth to include this issue in the next release for mainnet, but it's a question for discussion, what is the desired behaviour? I'm stick to the second option (change the contract to gain strictly more than a half) since it's natural for voting schemes to require 50+%. @txhsl @chenquanyu what is your opinion?

**Comment by txhsl** [comment]
According to N3.

> For any proposal to be approved, over 50% of committee members must reach an agreement before signing a transaction to update blockchain params on-chain.

I prefer the second option as well, we need `more than a half`, instead of `no less than a half`.
