### ISSUE TITLE
Update T4 system contracts

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#272]
# Rationale
After T4 launch there were updates in system contracts (#259, #267, #260). These updates are not currently deployed on T4.

# Implementation

We need to update all upgradable T4 system contracts. It requires voting from T4 CNs.

**Comment by AnnaShaleva** [comment]
@txhsl, @steven1227 please, write your opinion on this: should we perform it before or after v0.2.1 release? If we do this now, then if any issue happens during system contracts update in T4, then we'll be able to fix them before mainnet launch.

**Comment by gsmachado** [comment]
I believe doing it now is better.

**Comment by txhsl** [comment]
We can do it now, whether we can find or fix any other issue depends on time. At least so far, our testing work well with the latest codes.

**Comment by AnnaShaleva** [comment]
Let's do it now and see how the update goes on the real network.

**Comment by txhsl** [comment]
#259 is excluded from upgrade since we don't have any `initializer` or `reinitializer` functions in system contracts.

The implementation of Governance (`0x1212000000000000000000000000000000000001`) is scheduled from `0x1212100000000000000000000000000000000001` to `0xE79d7F408752f7F4aD45a2B213DBEe8BB4f90c0c`;
The implementation of Policy (`0x1212000000000000000000000000000000000002`) implementation is scheduled from `0x1212100000000000000000000000000000000002` to `0x4129B17Ed83705aFAFA3cdC3d1C289E54E27cA5B`;
The implementation of CommitteeMultiSig (`0x1212000000000000000000000000000000000007`) implementation is scheduled from `0x1212100000000000000000000000000000000007` to `0x642aEb65859100841b149F695643758d80D2541b`.

Will close this issue when their upgrades are finally executed.
