### ISSUE TITLE
Block Hash Inconsistent 

### ISSUE THREAD

**Issue by cloud8little** [bane-labs/go-ethereum#35]
#### System information

Geth version: Geth
Version: 1.13.1-stable
Git Commit: fd059099a26002fa053bac14a6ce42c7d671a338
Git Commit Date: 20231120
Architecture: amd64
Go Version: go1.21.3
OS & Version: Linux
Commit hash : fd059099a26002fa053bac14a6ce42c7d671a338

the consensus logs in miner node print a different block hash with the geth client. 

the hash use N3 block hash calculation,  ref: [dbft/block/block.go +165](https://github.com/nspcc-dev/dbft/blob/master/block/block.go#L165)

```go
// Hash implements Block interface.
func (b *neoBlock) Hash() (h util.Uint256) {
	if b.hash != nil {
		return *b.hash
	} else if b.transactions == nil {
		return
	}

	hash := crypto.Hash256(b.GetHashData())
	b.hash = &hash

	return hash
}
```

![7761c2766c31daa6c42f71d0085fc7f](https://github.com/bane-labs/go-ethereum/assets/34291844/6219ab4e-7e40-4b3d-96c6-53008ae7c8d8)

![48018c95c280bdc36b1a400124939a6](https://github.com/bane-labs/go-ethereum/assets/34291844/3a0cf120-52d2-4efc-ad3c-9f7fe4b516af)

**Comment by roman-khimov** [comment]
This one is known, a part of #29, but let's track this particular problem here for easier testing.

**Comment by AnnaShaleva** [comment]
This problem won't be solved since dBFT is designed to use blocks those hashable part doesn't contain signatures whereas sealed Eth block's hash includes block signatures. So currently dBFT uses block hash prior to block being sealed, exactly the same hash as miner/worker use:
https://github.com/bane-labs/go-ethereum/blob/7b56bf71af205bb183265e49513e6226d69a9f13/consensus/dbft/block.go#L116-L121
This method has proper documentation, and it's very convenient to track this hash in the node logs since miner/worker use the same hash to report about sealing tasks. So nothing unexpected happens in this issue, these are just two different hashes of the block (sealed/unsealed).

Technically, we may print the "honest" block hash in dBFT logs, to do this we need to provide dBFT context to the block's `Hash()` and construct proper block signatures in `Hash()` method, but I don't think it's a good reason to change dBFT interface. And thus, I'm closing this issue as not planned.
