### ISSUE TITLE
Proper PrepareRequest verification

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#53]
Currently (after #49) we have some basic PrepareRequest verification rules mostly focusing on block hash finalisation and checking that parent-related data (final parent hash and extra) filled properly (ref. `WithVerifyPrepareRequest` dBFT setting). What we're completely missing is proposed header fields verification. Within the scope of this issue we need to:
* check that transactions root retrieved from proposed transaction hashes matches the one specified in proposed header;
* check that receipts root declared in the proposed header matches the real receipts root got from transactions execution;
* check that proper difficulty is set
* perform any other necessary verification actions (they are very similar to the `VerifyHeader` consensus engine API).

As a result of this issue I'd expect that potentially invalid blocks won't be accepted by dBFT consensus and proposals (PrepareRequests) for such blocks will be immediately rejected by honest consensus nodes. Note that this issue is only about `WithVerifyPrepareRequest` callback extension.

**Comment by AnnaShaleva** [comment]
Ideally, it would be good to reuse most of `VerifyHeader` dBFT implementation for verification.

**Comment by txhsl** [comment]
The `minGasPrice` in Policy contract is, the minium allowed `tx.inner.gasPrice()` value of a transaction that the consensus should acknowledge. Our nodes in DBFT in N3 has some basic rules to compute the GAS cost, and `minGasPrice` works just like a combination of [ExecFeeFactor](https://github.com/neo-project/neo/blob/master/src/Neo/SmartContract/Native/PolicyContract.cs#L28C13-L28C13) and [StoragePrice](https://github.com/neo-project/neo/blob/master/src/Neo/SmartContract/Native/PolicyContract.cs#L33) in N3 policy. It is always checked when a new transaction arrives and being packaged, so that users cannot just pay 1 Gwei for his fee and execute his script. 

The way to get this value is reading from the current state, like in #6. 
https://github.com/bane-labs/go-ethereum/blob/940829a5239669a3694d360f55768a2b51a9916a/core/txpool/validation.go#L215

We have planned to add a limit of minium `baseFee` for EIP-1559 in Policy as well, but as far as I know, it has not been implemented yet.

**Comment by AnnaShaleva** [comment]
I'm a bit wrong in task description, most of header/block verification rules mentioned in this issue should be implemented as a part of block verification callback (`WithVerifyBlock`), ref. #65. But we should also double-check PrepareRequest verification callback to ensure that everything that possible is verified on PrepareRequest level.
