### ISSUE TITLE
Integrate transaction request mechanism

### ISSUE THREAD

**Issue by AnnaShaleva** [bane-labs/go-ethereum#59]
After #49 we have basic integration of dBFT with mempool and dBFT P2P service. What we're missing is a mechanism that allows `DBFT` service request specific range of transactions by hashes from the node's neighbors. Effectively, this is `WithRequestTx` dBFT callback setting that was mentioned in 6e8c8c798ddd753bf069e07d0800ffe4d524a797.

Of course, Geth node implementation already has a notion of P2P messages that allows to request specific transaction from nodes, see the https://github.com/bane-labs/go-ethereum/blob/94233fe05ce42ac2e4c4556ea1b3b871f2741964/eth/protocols/eth/peer.go#L492

So within the scope of this issue I'd expect to implement the following:
* provide a callback to `DBFT` instance in constructor or during initilization (similar to the way how `WithBroadcast`, `WithEthAPI` or `WithTxPool` work). This callback should broadcast `GetPooledTransactionsMsg` with the hashes given by dBFT.
* Properly integrate this callback with `WithRequestTx` dBFT callback.

**Comment by AnnaShaleva** [comment]
I'll attach here additional logs from @nicolegys. The case is that without this issue being implemented and under high transaction load, CN nodes own different sets of transactions and can't agree on some subsequent set because they can't request these transactions, current dBFT version relies only to a standard transaction broadcasting mechanism. This leads to CVs.

Originally posted by @nicolegys:
> I‘ve encountered something new when trying to reproduce  invalid merkle root problem on #79.
> My steps: 
> 1. start 4-cn privnet
> 2. send thousands of txs to node5
>
> Somehow, CNs have different txs in their txpools. So we can always see check prepare: some transactions are missing in cn1&cn3 log which results a CV.

Logs:
[4cn_geth_node_cn1.log](https://github.com/bane-labs/go-ethereum/files/13791754/4cn_geth_node_cn1.log)
[4cn_geth_node_cn2.log](https://github.com/bane-labs/go-ethereum/files/13791755/4cn_geth_node_cn2.log)
[4cn_geth_node_cn3.log](https://github.com/bane-labs/go-ethereum/files/13791756/4cn_geth_node_cn3.log)
[4cn_geth_node_cn4.log](https://github.com/bane-labs/go-ethereum/files/13791757/4cn_geth_node_cn4.log)[4cn_geth_node_node5.log](https://github.com/bane-labs/go-ethereum/files/13791758/4cn_geth_node_node5.log)
![d001e528e5dad39ae6979d8f4703a3d](https://github.com/bane-labs/go-ethereum/assets/22775709/1a4c59a2-de99-48ff-81e7-89624fd2e7b6)
![f4ba0d9dacf7bc58b087beb77c6bc70](https://github.com/bane-labs/go-ethereum/assets/22775709/1443ab65-bfd8-46c0-95ba-715f106d7e29)

Within the scope of this issue we need to ensure that integrated peer service is able to solve this problem (likely, a batch of subsequent CVs is needed with increasing dBFT timeouts, but still, the problem should be solved ones CNs have almost common set of transactions). If it's not the case, then additional investigation/adjustments may be needed.

**Comment by dusmart** [comment]
> The case is that without this issue being implemented and under high transaction load, CN nodes own different sets of transactions and can't agree on some subsequent set because they can't request these transactions, current dBFT version relies only to a standard transaction broadcasting mechanism. This leads to CVs.

Thanks for pointing this problem out.

There still exists an attack vector combined with the fact that transaction replacement (conflict transactions with the same sender and nonce) could only happen when the later one has 10% more fee than the first.

@AnnaShaleva @roman-khimov Please see if this exists now or not. I saw the comment https://github.com/bane-labs/go-ethereum/pull/87#issuecomment-1919315299 and high-priority P2P message enhancement https://github.com/bane-labs/go-ethereum/issues/46. They help a lot in this scenario. While when attack happened, CNs's peer do not even have the transactions they asked.

The attacker builds a lot of conflict transactions and spreads them around the whole network which would caused conflict mempools among those CNs. For ethereum, this is not a big issue because a slot can be empty if required votes can not be collected. For us, the whole blockchain may stuck here if the CNs have different mempools and transaction replacement won't happen. 

https://github.com/bane-labs/go-ethereum/blob/4d80ca7bfccd07e79197661f38732e577691d503/core/txpool/legacypool/legacypool.go#L759-L764
https://github.com/bane-labs/go-ethereum/blob/4d80ca7bfccd07e79197661f38732e577691d503/core/txpool/legacypool/legacypool.go#L145

FYI, NEO N3 still have this problem left unsolved even if the transaction replacement can happen easily there. My guess is that the problem is mostly related to dotnet's implementation and that `transaction replacement` is kinda of too easy and too cheap so that attacker could perform tx replacement all the way.

**Comment by AnnaShaleva** [comment]
> For us, the whole blockchain may stuck here if the CNs have different mempools and transaction replacement won't happen.

I think that starting from https://github.com/bane-labs/go-ethereum/pull/132 this problem not relevant anymore, because CN will receive transactions declared in PrepareRequest bypassing mempool, i.e. directly from the P2P service. And given the fact that consensus service is able to directly send transaction requests to the peers, eventually the consensus will get the required transactions.

> CNs's peer do not even have the transactions they asked.

This may be a problem, and it's connected with the network consistency. CVs and increasing dBFT timeouts are trying to solve this problem, so that eventually all nodes are able to share the same set of transactions if there's at least some connectivity between nodes clusters in the network. But still, this problem remains under continuous conflicting transactions spamming, that's why we have mempool tx priorities and fees restrictions. @roman-khimov, what do you think?

> FYI, NEO N3 still have this problem left unsolved even if the transaction replacement can happen easily there.

In NeoGo we have the same mechanism of transactions forwarding directly from P2P to dBFT, so the only problem that may occur here is that all node peers don't have the requested transaction. So I'm not sure what we can do here.

**Comment by roman-khimov** [comment]
@AnnaShaleva, this was discussed in https://github.com/neo-project/neo/issues/2862.
