### ISSUE TITLE
Create genesis block configuration for Bane testnet and mainnet

### ISSUE THREAD

**Issue by nicolegys** [bane-labs/go-ethereum#64]
Just a remind and for discussion, because I haven't seen anything about it in the existing issues.

Now in genesis block, timestamp is '0x0'.
```
{
    "jsonrpc": "2.0",
    "id": 3,
    "result": {
        "baseFeePerGas": "0x3b9aca00",
        "difficulty": "0x1",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000021d70769889c46db0a8b0b22245c7ffd956d343a6b78921e12d527e13a3907da9d6a1fd8e6f8d0abe0c8b1251697f919af32a42b7892b13026433b8d4d71adea0eeb18568fecf0fae0810a8520b438b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "gasLimit": "0x6acfc0",
        "gasUsed": "0x0",
        "hash": "0x98bb61fde1b49ef9e62992a28adfb71df99001a6dec2da1c5d534975f5611263",
        "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
        "miner": "0x0000000000000000000000000000000000000000",
        "mixHash": "0x04b83a5f5b6666f8bba8f78245767c5c1723842a8f442ff0dbe35141eefede71",
        "nonce": "0x0000000000000000",
        "number": "0x0",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
        "size": "0x332",
        "stateRoot": "0x7a77851842736c8672a67c64093fcdae5e1991f8cee5806a2d80a4b70a9749a9",
        "timestamp": "0x0",
        "totalDifficulty": "0x1",
        "transactions": [],
        "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
        "uncles": []
    }
}
```

**Comment by AnnaShaleva** [comment]
This issue is more related to the genesis block settings. Current privnet (if you're testing on privnet setup) has its own genesis block template (https://github.com/bane-labs/go-ethereum/blob/bane-main/privnet/four/genesis_template.json), and genesis block fields can be customized via `genesis_template.json` file. Since there's no custom timestamp set for the genesis block, then it's default (0), so this just work as expected (we didn't change this code, it's just a pure Geth source code). To customize genesis timestamp, add the corresponding field to https://github.com/bane-labs/go-ethereum/blob/c29386f34a30ae2120e661d988c4d10efe7018f9/privnet/four/node1/genesis_privnet.json#L28 and all other nodes' `genesis_privnet.json` files.

But the issue itself seems to be legit and related to the Bane testnet and mainnet settings. I'd suggest to rename it and put to backlog to create a special dedicated genesis settings files (or even default code-level genesis settings) that should be used for Bane testnet and mainnet, exactly as we have in NeoGo or NeoC# mainnet- and testnet- specific configuration files (https://github.com/nspcc-dev/neo-go/tree/master/config).

**Comment by AnnaShaleva** [comment]
@nicolegys, is it OK for you? Could you check that custom timestamp works properly if configured via privnet genesis json?

**Comment by nicolegys** [comment]
> @nicolegys, is it OK for you? Could you check that custom timestamp works properly if configured via privnet genesis json?

Sure! OK for me. Then I'll check it tomorrow.

**Comment by nicolegys** [comment]
@AnnaShaleva 
For private net, developers can customize genesis timestamp in `genesis.json`.
For Bane testnet and mainnet, it can be hardcoded as a default setting. 
https://github.com/bane-labs/go-ethereum/blob/c29386f34a30ae2120e661d988c4d10efe7018f9/core/genesis.go#L622-L633
I agree to put it to backlog and create a meaningful genesis time value for testnet and mainnet in the future.

**Comment by AnnaShaleva** [comment]
Native Treasury contract should be included into mainnet genesis config. Ref. #184.

**Comment by AnnaShaleva** [comment]
Testnet config is included, mainnet config not yet added.

**Comment by AnnaShaleva** [comment]
We need to include an updated version of GovernanceProxyUpgradeble (#259) into mainnet config.
